---
name: Bug Report
description: Raise a bug report
title: "Bug: "
labels: ["bug", "triage"]
assignees: DaveyJH
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? - Please be specific!
      description: Also tell us, what did you expect to happen/not happen?
      placeholder: "When using method `x`, I expected `y` and found that `z` happened"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the package did this happen on?
      value: "Version 1.1.2"
    validations:
      required: true
  - type: textarea
    id: operating-system
    attributes:
      label: Operating System / Environment
      description: Please provide details and versions regarding the OS and envirnomnent.
      placeholder: |
        Windows 10 Version 21H2

        Chrome browser Version 105.0.5195.127 (Official Build) (64-bit)

        GitHub pages deployed site https://myUser.github.io/myRepo

        Repository https://github.com/myUser/myRepo.git
    validations:
      required: true
  - type: textarea
    id: replicate
    attributes:
      label: How can I replicated the issue?
      description: Please provide specific steps, markdown syntax enabled.
      placeholder: |
        - install package with `npm i cheesestrings`
        - import using `require ("cheesestrings")`
        - string = "this is my string"
        - `string.reverse().capitalize()`
      render: markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output/errors
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
