---
name: Feature Request
description: Request a new feature or modification to an exisiting feature
title: "Feature: "
labels: ["enhancement", "triage"]
assignees: DaveyJH
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to have included/modified? - Please be specific!
      description: |
        Also tell us, what you expect to happen/not happen?
        Feel free to attach gifs/images that may help.
      placeholder: "As **a user** I would like **this feature**, so that I **can do this**."
    validations:
      required: true
  - type: dropdown
    id: new-feature
    attributes:
      label: Is this a new feature, or a modification?
      description: |
        If this is a bug about an existing feature, please fill in a [bug report](https://github.com/DaveyJH/form-test/issues/new?assignees=DaveyJH&labels=bug%2Ctriage&template=bug.yml&title=Bug%3A+) instead.
      options:
        - new feature
        - modification
  - type: input
    id: linked-issue
    attributes:
      label: Is this linked to an existing issue/PR?
      description: |
        "Please provide the issue/PR #."
      placeholder: "#1"
    validations:
      required: false
  - type: dropdown
    id: importance
    attributes:
      label: How important do you think this feature/modification is?
      description: |
        Is it an essential feature/modification? --> MUST!
        Would it vastly improve use, but is not causing a block? --> Should
        Is it something you feel would be nice to have, but is not a key feature? --> Could

        This will be up for review, the priority may be changed.
      options:
        - MUST!
        - should
        - could
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the package are you currently using?
      value: "Version 1.1.2"
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
